load: POSTWORLD
  main: pemapmodder\worldeditart\Main
  description: A powerful and advanced world editor
 -permissions:
 -  wea:
 -    description: Allow using all WorldEditArt functions
 -    children:
 -      wea.cmd:
 -        description: Allow using command /wea
 -      wea.sel:
 -        description: Allow making selections
 -        children:
 -          wea.sel.pt:
 -            description: Allow making point selections
 -            children:
 -              wea.sel.pt.here:
 -                description: Allow selecting a point by the player's self location
 -              wea.sel.pt.wand:
 -                description: Allow using subcommand plus selecting points using wands
 -          wea.sel.cub:
 -            description: Allow making cuboid selectiosn by any methods
 -            children:
 -              wea.sel.cub.selpts:
 -                description: Allow making cuboid selections by /wea sel <s1|s2> (using current selected point)
 -              wea.sel.cub.here:
 -                description: Allow making cuboid selections by /wea sel <1|2> (using current position)
 -              wea.sel.cub.dir:
 -                description: Allow making cuboid selections by /wea sel cub (directional selection)
 -          wea.sel.cyl:
 -            description: Allow making cylinder selections by /wea sel cyl
 -          wea.sel.sph:
 -            description: Allow making sphere selections by /wea sel sph
 -      wea.set:
 -        description: Allow using everything of /wea set
 -        children:
 -          wea.set.sphere:
 -            description: Allow setting the blocks in a selected sphere
 -          wea.set.cylinder:
 -            description: Allow setting the blocks in a selected cylinder
 -          wea.set.cuboid:
 -            description: Allow setting the blocks in a selected cuboid
 -      wea.replace:
 -        description: Allow using everything of /wea replace
 -        children:
 -          wea.replace.sphere:
 -            description: Allow replacing the blocks in a selected sphere
 -          wea.replace.cylinder:
 -            description: Allow replacing the blocks in a selected cylinder
 -          wea.replace.cuboid:
 -            description: Allow replacing the blocks in a selected cuboid
 -      wea.test:
 -        description: Allow using everything of /wea test
 -        children:
 -          wea.test.sphere:
 -            description: Allow testing sphere selections
 -          wea.test.cylinder:
 -            description: Allow testing cylinder selections
 -          wea.test.cuboid:
 -            description: Allow testing cuboid selections
 -      wea.wand:
 -        description: Allow using everything of /wea wand
 -        children:
 -          wea.wand.check:
 -            description: Allow checking own wand
 -          wea.wand.set:
 -            description: Allow setting own wand
 -            children:
 -              wea.wand.set.hand:
 -                description: Allow using subcommand /wea wand hand
 -              wea.wand.set.named:
 -                description: Allow using subcommand /wea wand <id|name>
 -      wea.macro:
 -        description: Allow using all features of macros
 -        children:
 -          wea.macro.record:
 -            description: Allow recording macros
 -          wea.macro.run:
 -            description: Allow running macros
 -      wea.anchor:
 -        description: Allow managing everything about the player's own anchor
 -        children:
 -          wea.anchor.view:
 -            description: Allow viewing own anchor
 -          wea.anchor.set:
 -            description: Allow setting own anchor via all methods
 -            children:
 -              wea.anchor.set.here:
 -                description: Allow setting own anchor by current position
 -              wea.anchor.set.sel:
 -                description: Allow setting own anchor by the player's selected point
 -      wea.clipboard:
 -        description: Allow doing all clipboard-related things
 -        children:
 -          wea.clipboard.copy:
 -            description: Allow doing all kinds of copying
 -            children:
 -              wea.clipboard.copy.cuboid:
 -                description: Allow copying cuboids
 -              wea.clipboard.copy.cylinder:
 -                description: Allow copying cylinders
 -              wea.clipboard.copy.sphere:
 -                description: Allow copying spheres
 -          wea.clipboard.cut:
 -            description: Allow doing all kinds of cutting
 -            children:
 -              wea.clipboard.cut.cuboid:
 -                description: Allow cutting cuboids
 -              wea.clipboard.cut.cylinder:
 -                description: Allow cutting cylinders
 -              wea.clipboard.cut.sphere:
 -                description: Allow cutting spheres
 -          wea.clipboard.paste:
 -            description: Allow pastin
 -          wea.clipboard.global:
 -            description: Allow cutting/copying into the global clipboard
